const { chromium } = require('playwright');

const urls = [
  'https://sanand0.github.io/tdsdata/js_table/?seed=87',
  'https://sanand0.github.io/tdsdata/js_table/?seed=88',
  'https://sanand0.github.io/tdsdata/js_table/?seed=89',
  'https://sanand0.github.io/tdsdata/js_table/?seed=90',
  'https://sanand0.github.io/tdsdata/js_table/?seed=91',
  'https://sanand0.github.io/tdsdata/js_table/?seed=92',
  'https://sanand0.github.io/tdsdata/js_table/?seed=93',
  'https://sanand0.github.io/tdsdata/js_table/?seed=94',
  'https://sanand0.github.io/tdsdata/js_table/?seed=95',
  'https://sanand0.github.io/tdsdata/js_table/?seed=96',
];

(async () => {
  const browser = await chromium.launch();
  let grandTotal = 0;

  for (const url of urls) {
    const page = await browser.newPage();
    await page.goto(url);

    // Wait for the table to load (it's dynamically generated by JS)
    await page.waitForSelector('table');

    // Grab all table cell text, parse numbers, and sum them
    const pageSum = await page.evaluate(() => {
      const cells = document.querySelectorAll('table td');
      let sum = 0;
      cells.forEach(cell => {
        const val = parseFloat(cell.innerText);
        if (!isNaN(val)) sum += val;
      });
      return sum;
    });

    console.log(`Sum for ${url}: ${pageSum}`);
    grandTotal += pageSum;
    await page.close();
  }

  await browser.close();
  console.log(`Total sum across all pages: ${grandTotal}`);
})();
